language: node_js
sudo: false

addons:
  sauce_connect:
    # Update SAUCE_USERNAME / SAUCE_ACCESS_KEY in travis if necessary
    # https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
    sauce_connect: true

cache:
  timeout: 1000
  directories:
    - $HOME/.npm

env:
  matrix:
  - NODE_VER=8
  - NODE_VER=10
matrix:
  fast_finish: true

before_install:
  - nvm install $NODE_VER
  - npm install -g npm npx && node -v && npm -v

install:
  - npm install

script:
  - npm test
